install.packages("ggplot2", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
install.packages("ggmap", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
install.packages("dplyr", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
install.packages("fossil", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
install.packages("RMySQL", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
install.packages("labeling", repos="http://cran.r-project.org", lib="/home/ubuntu/projects/Rlibs/")
