
USE distance_effects;


-- ORGANIZE THE BUSINESSES INTO AREAS THAT WE CAN EASILY IDENTIFY IN A QUERY
-- THIS INVOLVES ADDING A NEW COLUMN AREA.
-- WE THEN REMOVE THE COLUMN 'STATE' AS WE HAVE NO USE FOR IT.

ALTER TABLE Business
ADD COLUMN Area varchar(6)
;

UPDATE Business
SET Area = State
;

UPDATE Business
SET Area = 'EDI'
WHERE State IN ('HAM', 'XGL', 'NTH', 'KHL', 'SCB', 'FIF', 'ELN', 'MLN', 'EDH')
;

UPDATE Business
SET Area = 'KRL'
WHERE State IN ('NW', 'RP', 'BW')
;

ALTER TABLE Business
DROP COLUMN State
;
